/**
 * demo FrontAPI
 * demo FrontAPI
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient', '../model/HostVO'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./HostVO'));
  } else {
    // Browser globals (root is window)
    if (!root.DemoFrontApi) {
      root.DemoFrontApi = {};
    }
    root.DemoFrontApi.HostQueryResultVO = factory(root.DemoFrontApi.ApiClient, root.DemoFrontApi.HostVO);
  }
}(this, function(ApiClient, HostVO) {
  'use strict';




  /**
   * The HostQueryResultVO model module.
   * @module model/HostQueryResultVO
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>HostQueryResultVO</code>.
   * @alias module:model/HostQueryResultVO
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>HostQueryResultVO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HostQueryResultVO} obj Optional instance to populate.
   * @return {module:model/HostQueryResultVO} The populated <code>HostQueryResultVO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('totalCount')) {
        obj['totalCount'] = ApiClient.convertToType(data['totalCount'], 'Integer');
      }
      if (data.hasOwnProperty('pageIndex')) {
        obj['pageIndex'] = ApiClient.convertToType(data['pageIndex'], 'Integer');
      }
      if (data.hasOwnProperty('pageSize')) {
        obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Integer');
      }
      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], [HostVO]);
      }
    }
    return obj;
  }

  /**
   * 记录总数
   * @member {Integer} totalCount
   */
  exports.prototype['totalCount'] = undefined;
  /**
   * 当前页码
   * @member {Integer} pageIndex
   */
  exports.prototype['pageIndex'] = undefined;
  /**
   * 每页记录数
   * @member {Integer} pageSize
   */
  exports.prototype['pageSize'] = undefined;
  /**
   * 主机列表
   * @member {Array.<module:model/HostVO>} data
   */
  exports.prototype['data'] = undefined;



  return exports;
}));


