/**
 * demo FrontAPI
 * demo FrontAPI
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DemoFrontApi) {
      root.DemoFrontApi = {};
    }
    root.DemoFrontApi.HostVO = factory(root.DemoFrontApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The HostVO model module.
   * @module model/HostVO
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>HostVO</code>.
   * @alias module:model/HostVO
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>HostVO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HostVO} obj Optional instance to populate.
   * @return {module:model/HostVO} The populated <code>HostVO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('ipAddr')) {
        obj['ipAddr'] = ApiClient.convertToType(data['ipAddr'], 'String');
      }
      if (data.hasOwnProperty('osType')) {
        obj['osType'] = ApiClient.convertToType(data['osType'], 'String');
      }
      if (data.hasOwnProperty('cpuCores')) {
        obj['cpuCores'] = ApiClient.convertToType(data['cpuCores'], 'Integer');
      }
      if (data.hasOwnProperty('memorySize')) {
        obj['memorySize'] = ApiClient.convertToType(data['memorySize'], 'Number');
      }
      if (data.hasOwnProperty('diskCapacity')) {
        obj['diskCapacity'] = ApiClient.convertToType(data['diskCapacity'], 'Number');
      }
    }
    return obj;
  }

  /**
   * ID
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * 名称
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * IP地址
   * @member {String} ipAddr
   */
  exports.prototype['ipAddr'] = undefined;
  /**
   * 操作系统
   * @member {String} osType
   */
  exports.prototype['osType'] = undefined;
  /**
   * CPU核数
   * @member {Integer} cpuCores
   */
  exports.prototype['cpuCores'] = undefined;
  /**
   * 内存大小
   * @member {Number} memorySize
   */
  exports.prototype['memorySize'] = undefined;
  /**
   * 磁盘容量
   * @member {Number} diskCapacity
   */
  exports.prototype['diskCapacity'] = undefined;



  return exports;
}));


