/**
 * demo FrontAPI
 * demo FrontAPI
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DemoFrontApi) {
      root.DemoFrontApi = {};
    }
    root.DemoFrontApi.TodoVO = factory(root.DemoFrontApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The TodoVO model module.
   * @module model/TodoVO
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>TodoVO</code>.
   * @alias module:model/TodoVO
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>TodoVO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TodoVO} obj Optional instance to populate.
   * @return {module:model/TodoVO} The populated <code>TodoVO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Integer');
      }
      if (data.hasOwnProperty('createUser')) {
        obj['createUser'] = ApiClient.convertToType(data['createUser'], 'String');
      }
      if (data.hasOwnProperty('dealsUser')) {
        obj['dealsUser'] = ApiClient.convertToType(data['dealsUser'], 'String');
      }
      if (data.hasOwnProperty('hasCompleted')) {
        obj['hasCompleted'] = ApiClient.convertToType(data['hasCompleted'], 'Boolean');
      }
      if (data.hasOwnProperty('createTime')) {
        obj['createTime'] = ApiClient.convertToType(data['createTime'], 'Integer');
      }
      if (data.hasOwnProperty('content')) {
        obj['content'] = ApiClient.convertToType(data['content'], 'String');
      }
      if (data.hasOwnProperty('todoTime')) {
        obj['todoTime'] = ApiClient.convertToType(data['todoTime'], 'Integer');
      }
      if (data.hasOwnProperty('dealsTime')) {
        obj['dealsTime'] = ApiClient.convertToType(data['dealsTime'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * id
   * @member {Integer} id
   */
  exports.prototype['id'] = undefined;
  /**
   * 创建用户
   * @member {String} createUser
   */
  exports.prototype['createUser'] = undefined;
  /**
   * 处理用户
   * @member {String} dealsUser
   */
  exports.prototype['dealsUser'] = undefined;
  /**
   * 是否已经完成
   * @member {Boolean} hasCompleted
   */
  exports.prototype['hasCompleted'] = undefined;
  /**
   * 创建时间
   * @member {Integer} createTime
   */
  exports.prototype['createTime'] = undefined;
  /**
   * 待办内容
   * @member {String} content
   */
  exports.prototype['content'] = undefined;
  /**
   * 待办时间
   * @member {Integer} todoTime
   */
  exports.prototype['todoTime'] = undefined;
  /**
   * 处理时间
   * @member {Integer} dealsTime
   */
  exports.prototype['dealsTime'] = undefined;



  return exports;
}));


