/**
 * demo FrontAPI
 * demo FrontAPI
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient', '../model/HostVO', '../model/ErrorResponse', '../model/HostQueryResultVO'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/HostVO'), require('../model/ErrorResponse'), require('../model/HostQueryResultVO'));
  } else {
    // Browser globals (root is window)
    if (!root.DemoFrontApi) {
      root.DemoFrontApi = {};
    }
    root.DemoFrontApi.HostmgrApi = factory(root.DemoFrontApi.ApiClient, root.DemoFrontApi.HostVO, root.DemoFrontApi.ErrorResponse, root.DemoFrontApi.HostQueryResultVO);
  }
}(this, function(ApiClient, HostVO, ErrorResponse, HostQueryResultVO) {
  'use strict';

  /**
   * Hostmgr service.
   * @module api/HostmgrApi
   * @version 2.0.0
   */

  /**
   * Constructs a new HostmgrApi. 
   * @alias module:api/HostmgrApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createHost operation.
     * @callback module:api/HostmgrApi~createHostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HostVO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 新建主机
     * 新建一个主机
     * @param {module:model/HostVO} hostVO 主机信息
     * @param {module:api/HostmgrApi~createHostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/HostVO}
     */
    this.createHost = function(hostVO, callback) {
      var postBody = hostVO;

      // verify the required parameter 'hostVO' is set
      if (hostVO == undefined || hostVO == null) {
        throw "Missing the required parameter 'hostVO' when calling createHost";
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = HostVO;

      return this.apiClient.callApi(
        '/hosts/create', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteHostById operation.
     * @callback module:api/HostmgrApi~deleteHostByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HostVO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 根据ID删除主机
     * 删除ID指定的主机
     * @param {String} id 待删除主机的ID
     * @param {module:api/HostmgrApi~deleteHostByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/HostVO}
     */
    this.deleteHostById = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling deleteHostById";
      }


      var pathParams = {
      };
      var queryParams = {
        'id': id
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = HostVO;

      return this.apiClient.callApi(
        '/hosts/delete', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getHostById operation.
     * @callback module:api/HostmgrApi~getHostByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HostVO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 根据ID加载主机
     * 返回ID指定的主机信息
     * @param {String} id 主机的ID
     * @param {module:api/HostmgrApi~getHostByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/HostVO}
     */
    this.getHostById = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling getHostById";
      }


      var pathParams = {
      };
      var queryParams = {
        'id': id
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = HostVO;

      return this.apiClient.callApi(
        '/hosts/get', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the queryHosts operation.
     * @callback module:api/HostmgrApi~queryHostsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HostQueryResultVO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 查询满足条件的主机
     * 根据条件查询主机
     * @param {Object} opts Optional parameters
     * @param {String} opts.queryKey 名称或IP地址，模糊匹配
     * @param {Integer} opts.pageIndex 查询页号，值为 0 时表示第1页 (default to 0)
     * @param {Integer} opts.pageSize 每页行数，值为 -1 时表示不分页 (default to 50)
     * @param {module:api/HostmgrApi~queryHostsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/HostQueryResultVO}
     */
    this.queryHosts = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'query_key': opts['queryKey'],
        'page_index': opts['pageIndex'],
        'page_size': opts['pageSize']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = HostQueryResultVO;

      return this.apiClient.callApi(
        '/hosts/query', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateHostById operation.
     * @callback module:api/HostmgrApi~updateHostByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HostVO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 根据ID更新主机
     * 更新IP对应的主机
     * @param {module:model/HostVO} hostVO 待更新的主机信息
     * @param {module:api/HostmgrApi~updateHostByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/HostVO}
     */
    this.updateHostById = function(hostVO, callback) {
      var postBody = hostVO;

      // verify the required parameter 'hostVO' is set
      if (hostVO == undefined || hostVO == null) {
        throw "Missing the required parameter 'hostVO' when calling updateHostById";
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = HostVO;

      return this.apiClient.callApi(
        '/hosts/update', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
