/**
 * alertagent FrontAPI
 * alertagent FrontAPI
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient', '../model/TodoVO', '../model/ErrorResponse', '../model/DutyVO'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/TodoVO'), require('../model/ErrorResponse'), require('../model/DutyVO'));
  } else {
    // Browser globals (root is window)
    if (!root.AlertagentFrontApi) {
      root.AlertagentFrontApi = {};
    }
    root.AlertagentFrontApi.RotatodoApi = factory(root.AlertagentFrontApi.ApiClient, root.AlertagentFrontApi.TodoVO, root.AlertagentFrontApi.ErrorResponse, root.AlertagentFrontApi.DutyVO);
  }
}(this, function(ApiClient, TodoVO, ErrorResponse, DutyVO) {
  'use strict';

  /**
   * Rotatodo service.
   * @module api/RotatodoApi
   * @version 2.0.0
   */

  /**
   * Constructs a new RotatodoApi. 
   * @alias module:api/RotatodoApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the deleteTodoById operation.
     * @callback module:api/RotatodoApi~deleteTodoByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TodoVO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 删除待办事项
     * 删除待办事项
     * @param {Integer} id 待办事项ID
     * @param {module:api/RotatodoApi~deleteTodoByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TodoVO}
     */
    this.deleteTodoById = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling deleteTodoById";
      }


      var pathParams = {
      };
      var queryParams = {
        'id': id
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = TodoVO;

      return this.apiClient.callApi(
        '/todos/delete', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the insertTodo operation.
     * @callback module:api/RotatodoApi~insertTodoCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TodoVO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 创建待办事项
     * 创建待办事项
     * @param {Object} opts Optional parameters
     * @param {module:model/TodoVO} opts.createTodo 待办事项
     * @param {module:api/RotatodoApi~insertTodoCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TodoVO}
     */
    this.insertTodo = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['createTodo'];


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = TodoVO;

      return this.apiClient.callApi(
        '/todos/create', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the queryByContent operation.
     * @callback module:api/RotatodoApi~queryByContentCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/TodoVO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 根据条件查询待办事项
     * 根据条件查询待办事项
     * @param {Integer} dutyDate 排班日期
     * @param {String} content 任务内容
     * @param {module:api/RotatodoApi~queryByContentCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/TodoVO>}
     */
    this.queryByContent = function(dutyDate, content, callback) {
      var postBody = null;

      // verify the required parameter 'dutyDate' is set
      if (dutyDate == undefined || dutyDate == null) {
        throw "Missing the required parameter 'dutyDate' when calling queryByContent";
      }

      // verify the required parameter 'content' is set
      if (content == undefined || content == null) {
        throw "Missing the required parameter 'content' when calling queryByContent";
      }


      var pathParams = {
      };
      var queryParams = {
        'dutyDate': dutyDate,
        'content': content
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [TodoVO];

      return this.apiClient.callApi(
        '/todos/search', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the queryDutys operation.
     * @callback module:api/RotatodoApi~queryDutysCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/DutyVO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 获取某天的排班信息
     * 获取某天的排班信息
     * @param {Integer} dutyDate 排班日期
     * @param {module:api/RotatodoApi~queryDutysCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/DutyVO>}
     */
    this.queryDutys = function(dutyDate, callback) {
      var postBody = null;

      // verify the required parameter 'dutyDate' is set
      if (dutyDate == undefined || dutyDate == null) {
        throw "Missing the required parameter 'dutyDate' when calling queryDutys";
      }


      var pathParams = {
      };
      var queryParams = {
        'dutyDate': dutyDate
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [DutyVO];

      return this.apiClient.callApi(
        '/dutys/query', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the selectTodoFindAll operation.
     * @callback module:api/RotatodoApi~selectTodoFindAllCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/TodoVO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 查询待办事项
     * 查询待办事项
     * @param {Integer} dutyDate 排班日期
     * @param {module:api/RotatodoApi~selectTodoFindAllCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/TodoVO>}
     */
    this.selectTodoFindAll = function(dutyDate, callback) {
      var postBody = null;

      // verify the required parameter 'dutyDate' is set
      if (dutyDate == undefined || dutyDate == null) {
        throw "Missing the required parameter 'dutyDate' when calling selectTodoFindAll";
      }


      var pathParams = {
      };
      var queryParams = {
        'dutyDate': dutyDate
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [TodoVO];

      return this.apiClient.callApi(
        '/todos/query', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateTodoById operation.
     * @callback module:api/RotatodoApi~updateTodoByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TodoVO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 更新待办事项
     * 更新待办事项
     * @param {Object} opts Optional parameters
     * @param {module:model/TodoVO} opts.updateTodo 待办事项
     * @param {module:api/RotatodoApi~updateTodoByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TodoVO}
     */
    this.updateTodoById = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['updateTodo'];


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = TodoVO;

      return this.apiClient.callApi(
        '/todos/update', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
